language: python

sudo: false

python:
  - "3.6"
  - "3.5"
  - "3.4"

before_install: 
  - pip install --upgrade pip

install: 
  - pip install tinydb cryptography pyperclip

script:
  - python keyring.py --help